### ISSUE TITLE
Request for HMR2.0 checkpoint finetuned on Harmony4D

### ISSUE THREAD

**Issue by Kelly510** [jyuntins/harmony4d#4]
Hi! This work is amazing. 
Wondering if you can release the HMR 2.0 model finetuned on the dataset? It would provide great convenience for me.

**Comment by Kelly510** [comment]
Another question is: What coordinate system is used for the data in the SMPL npy files? Looking forward to your reply.

**Comment by jyuntins** [comment]
Hi sorry for the late reply. The smpl is in a world coordinate system, which is obtained from colmap. We have further ensured this coordinate system to be gravity aligned. In terms of the hmr2.0 model, I think it’s this one:  [link](https://drive.google.com/file/d/1RoVg8Rn-dSAtRkKBMon6lZbxTCXPwXTM/view?usp=drivesdk)
